### ISSUE TITLE
Issue with the poisson example

### ISSUE THREAD

**Issue by Fvergnet** [barkm/torch-fenics#1]
Hi !
I tried to install your package and to test your poisson example, but an issue occured.
This is how I installed everything: 
```
 conda create --name fenics_torch
 source activate fenics_torch
 conda install -c conda-forge fenics=2018.1.0
 pip install --process-dependency-links git+https://github.com/pbarkm/torch-fenics.git@master
```

And this is the output of `python poisson.py`:
```
/Users/user/anaconda2/envs/fenics_torch/lib/python3.6/site-packages/ffc/uflacs/analysis/dependencies.py:61: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  active[targets] = 1
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
/Users/user/anaconda2/envs/fenics_torch/lib/python3.6/site-packages/ffc/uflacs/analysis/dependencies.py:61: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  active[targets] = 1
Traceback (most recent call last):
  File "poisson.py", line 69, in <module>
    J.backward()
  File "/Users/user/anaconda2/envs/fenics_torch/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/user/anaconda2/envs/fenics_torch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/Users/user/anaconda2/envs/fenics_torch/lib/python3.6/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/Users/user/anaconda2/envs/fenics_torch/lib/python3.6/site-packages/torch_fenics/torch_fenics.py", line 127, in backward
    adj_value=adj_value)
TypeError: compute_gradient() got an unexpected keyword argument 'adj_value'
```

**Comment by barkm** [comment]
Hi!

Seems like the correct fork of pyadjoint is not installed. I will have a look at the install script. 

For now you can install the dependencies manually 

```
conda create --name torch-fenics python=3.6
conda activate torch-fenics
conda install -c conda-forge fenics=2018.1.0
conda install -c pytorch pytorch=0.4.1
pip install git+https://bitbucket.org/barkm/pyadjoint.git@torch-fenics
pip install git+https://github.com/pbarkm/torch-fenics.git@master
```
